from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.audit import log_action
from app.models.models import Investigation, Case, Report, User, Institution, Evidence
from app.schemas.schemas import ReportOut
from app.auth.dependencies import get_current_user

router = APIRouter(prefix="/api/reports", tags=["reports"])


class CreateReportRequest(BaseModel):
    investigation_id: str


def _render_report_html(case: Case, inv: Investigation, institution: Institution,
                         investigator: User, evidence: list[Evidence], report_number: str) -> str:
    factors_html = "".join(
        f"<tr><td>{f['label']}</td><td>+{f['weight']}</td><td>{f['detail']}</td></tr>"
        for f in inv.risk_factors
    )
    findings_html = "".join(
        f"<li><strong>{f['title']}</strong> ({f['severity'].upper()}) — {f['description']} "
        f"[+{f['risk_contribution']}]</li>"
        for f in inv.findings
    )
    evidence_html = "".join(
        f"<tr><td>{e.evidence_code}</td><td>{e.transaction_hash[:18]}...</td>"
        f"<td>{e.source_wallet[:12]}...</td><td>{e.destination_wallet[:12]}...</td>"
        f"<td>{e.amount} {e.token}</td><td>{e.timestamp}</td><td>{e.finding_supported}</td></tr>"
        for e in evidence
    )
    timeline_html = "".join(
        f"<li>{t['timestamp']} — {t['event']} ({t['detail']})</li>" for t in inv.timeline
    )

    return f"""
    <html>
    <head><meta charset="utf-8"><title>ATHENS Investigation Report {report_number}</title>
    <style>
      body {{ font-family: Arial, Helvetica, sans-serif; color: #0f172a; margin: 40px; }}
      h1 {{ color: #0b2545; border-bottom: 3px solid #0ea5e9; padding-bottom: 8px; }}
      h2 {{ color: #0b2545; margin-top: 28px; }}
      table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
      th, td {{ border: 1px solid #cbd5e1; padding: 6px 8px; font-size: 13px; text-align: left; }}
      th {{ background: #0b2545; color: white; }}
      .badge {{ display:inline-block; padding: 4px 12px; border-radius: 6px; color: white; font-weight:bold; }}
      .meta {{ color:#475569; font-size: 13px; }}
    </style>
    </head>
    <body>
      <h1>ATHENS — Investigation Report</h1>
      <p class="meta">Report No: {report_number} &nbsp;|&nbsp; Generated: {datetime.utcnow().isoformat()} UTC</p>
      <p class="meta">Institution: {institution.name} &nbsp;|&nbsp; Investigator: {investigator.full_name}</p>

      <h2>Case Summary</h2>
      <p><strong>Case ID:</strong> {case.case_number}<br/>
         <strong>Title:</strong> {case.title}<br/>
         <strong>Wallet Address:</strong> {case.wallet_address or 'N/A'}<br/>
         <strong>Transaction Hash:</strong> {case.transaction_hash or 'N/A'}<br/>
         <strong>Blockchain:</strong> {case.network}<br/>
         <strong>Fraud Type:</strong> {case.fraud_type}</p>

      <h2>Risk Assessment</h2>
      <p><span class="badge" style="background:#dc2626;">{inv.risk_level.value}</span>
         &nbsp; Score: <strong>{inv.risk_score}/100</strong></p>
      <table><thead><tr><th>Factor</th><th>Weight</th><th>Detail</th></tr></thead>
      <tbody>{factors_html}</tbody></table>

      <h2>Executive Summary</h2>
      <p>{inv.executive_summary}</p>

      <h2>Key Findings</h2>
      <ul>{findings_html}</ul>

      <h2>Probable Destination</h2>
      <p><strong>{inv.probable_entity_name}</strong> — Confidence: {inv.probable_entity_confidence}%<br/>
         {inv.probable_entity_reasoning}</p>

      <h2>Evidence</h2>
      <table><thead><tr><th>ID</th><th>Tx Hash</th><th>Source</th><th>Destination</th>
      <th>Amount</th><th>Timestamp</th><th>Finding</th></tr></thead>
      <tbody>{evidence_html}</tbody></table>

      <h2>Investigation Timeline</h2>
      <ul>{timeline_html}</ul>

      <h2>Investigator Notes</h2>
      <p>{inv.investigator_notes or '(No notes recorded)'}</p>

      <p class="meta">This report was generated by ATHENS using simulated blockchain analytics
      for demonstration purposes (Smart India Hackathon prototype, Problem Statement 26183).</p>
    </body>
    </html>
    """


@router.get("", response_model=list[ReportOut])
def list_reports(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    q = db.query(Report)
    if user.role.value != "SUPER_ADMIN":
        q = q.filter(Report.institution_id == user.institution_id)
    items = q.order_by(Report.created_at.desc()).all()
    return [ReportOut.model_validate(r) for r in items]


@router.post("", response_model=ReportOut)
def generate_report(payload: CreateReportRequest, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    q = db.query(Investigation)
    if user.role.value != "SUPER_ADMIN":
        q = q.filter(Investigation.institution_id == user.institution_id)
    inv = q.filter(Investigation.id == payload.investigation_id).first()
    if not inv:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Investigation not found")

    case = db.query(Case).filter(Case.id == inv.case_id).first()
    institution = db.query(Institution).filter(Institution.id == inv.institution_id).first()
    evidence = db.query(Evidence).filter(Evidence.investigation_id == inv.id).all()

    count = db.query(Report).count() + 1
    report_number = f"RPT-{datetime.utcnow().year}-{count:04d}"

    html = _render_report_html(case, inv, institution, user, evidence, report_number)

    report = Report(
        institution_id=inv.institution_id,
        investigation_id=inv.id,
        report_number=report_number,
        generated_by=user.id,
        html_content=html,
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    log_action(db, "Report generated", institution_id=user.institution_id, user_id=user.id,
               resource_type="report", resource_id=report.id, details=report_number)

    return ReportOut.model_validate(report)


@router.get("/{report_id}", response_model=ReportOut)
def get_report(report_id: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    q = db.query(Report)
    if user.role.value != "SUPER_ADMIN":
        q = q.filter(Report.institution_id == user.institution_id)
    report = q.filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return ReportOut.model_validate(report)
